'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Mälupulk.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo on
        '''setlocal EnableDelayedExpansion EnableExtensions
        '''for %%a in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
        '''if exist &quot;%%a\E_INFO\edition.txt&quot; set drv=%%a
        ''')
        ''':backstart
        '''if not exist %drv%\E_INFO\communicate.cmd exit
        '''call %drv%\E_INFO\communicate.cmd
        '''ping localhost -n 2 &gt;nul
        '''del %drv%\E_INFO\communicate.cmd
        '''if &quot;%br%&quot;==&quot;backup&quot; goto backup
        '''if &quot;%br%&quot;==&quot;restore&quot; goto restore
        '''if &quot;%br%&quot;==&quot;&quot; exit
        '''echo Destination: %destination%
        '''echo Backup cat 1: %cat1%
        '''echo Backup cat 2: %cat2%
        '''e [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property br() As String
            Get
                Return ResourceManager.GetString("br", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''setlocal EnableDelayedExpansion EnableExtensions
        '''set driv=%1
        '''set driv=!driv:+= !
        '''for /d /r %%a in (&quot;!driv!&quot;) do set /a mc+=1
        '''@echo !mc!
        '''.
        '''</summary>
        Friend ReadOnly Property count() As String
            Get
                Return ResourceManager.GetString("count", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''if exist &quot;K:\E_INFO\edition.txt&quot; set drv=K:&amp;goto backstart
        '''if exist &quot;A:\E_INFO\edition.txt&quot; set drv=A:&amp;goto backstart
        '''if exist &quot;B:\E_INFO\edition.txt&quot; set drv=B:&amp;goto backstart
        '''if exist &quot;C:\E_INFO\edition.txt&quot; set drv=C:&amp;goto backstart
        '''if exist &quot;D:\E_INFO\edition.txt&quot; set drv=D:&amp;goto backstart
        '''if exist &quot;E:\E_INFO\edition.txt&quot; set drv=E:&amp;goto backstart
        '''if exist &quot;F:\E_INFO\edition.txt&quot; set drv=F:&amp;goto backstart
        '''if exist &quot;G:\E_INFO\edition.txt&quot; set drv=G:&amp;goto backstart
        '''if exist &quot;H:\E_INFO\e [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property del() As String
            Get
                Return ResourceManager.GetString("del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f22170384() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f22170384", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property italic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mas_flash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mas_flash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sketch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sketch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strikeout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strikeout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property underline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("underline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
